"""Port modes of the sv2vhdl library entities (generated: do not edit).

tgt-vhdl instantiates these as sv2vhdl.sv_* (gates, MOS switches, pulls,
tran switches, three-state buffers); their declarations are not in
design.vhd.  Generated by vamos.ams.vhdl.render_modes_module() from nvc's
lib/sv2vhdl/{sv_gates.vhd,sv_mos.vhd,sv_pull.vhd,sv_tran.vhd,sv_tristate.vhd};
tests/vamos/test_ams_vhdl.py regenerates it and compares.
"""

from __future__ import annotations

from typing import Dict

SOURCES = ("sv_gates.vhd", "sv_mos.vhd", "sv_pull.vhd", "sv_tran.vhd", "sv_tristate.vhd")

# entity -> port -> mode (in | out | inout)
MODES: Dict[str, Dict[str, str]] = {
    "sv_alias": {"a": "inout", "b": "inout"},
    "sv_and": {"y": "out", "a": "in"},
    "sv_buf": {"y": "out", "a": "in"},
    "sv_bufif0": {"y": "out", "data": "in", "ctrl": "in"},
    "sv_bufif1": {"y": "out", "data": "in", "ctrl": "in"},
    "sv_cmos": {"y": "out", "data": "in", "ngate": "in", "pgate": "in"},
    "sv_nand": {"y": "out", "a": "in"},
    "sv_nmos": {"y": "out", "data": "in", "gate": "in"},
    "sv_nor": {"y": "out", "a": "in"},
    "sv_not": {"y": "out", "a": "in"},
    "sv_notif0": {"y": "out", "data": "in", "ctrl": "in"},
    "sv_notif1": {"y": "out", "data": "in", "ctrl": "in"},
    "sv_or": {"y": "out", "a": "in"},
    "sv_pmos": {"y": "out", "data": "in", "gate": "in"},
    "sv_pulldown": {"y": "out"},
    "sv_pullup": {"y": "out"},
    "sv_rcmos": {"y": "out", "data": "in", "ngate": "in", "pgate": "in"},
    "sv_rnmos": {"y": "out", "data": "in", "gate": "in"},
    "sv_rpmos": {"y": "out", "data": "in", "gate": "in"},
    "sv_rtran": {"a": "inout", "b": "inout"},
    "sv_rtranif0": {"a": "inout", "b": "inout", "ctrl": "in"},
    "sv_rtranif1": {"a": "inout", "b": "inout", "ctrl": "in"},
    "sv_strength_buf": {"y": "inout", "data": "in"},
    "sv_tran": {"a": "inout", "b": "inout"},
    "sv_tranif0": {"a": "inout", "b": "inout", "ctrl": "in"},
    "sv_tranif1": {"a": "inout", "b": "inout", "ctrl": "in"},
    "sv_xnor": {"y": "out", "a": "in"},
    "sv_xor": {"y": "out", "a": "in"},
}
