#!/usr/bin/env python3
"""Generate a VHDL force/release block for every register signal in an
sv2vhdl-translated entity.

Reads the translated <dut>.vhd file, finds every `signal foo : <type>`
declaration in the architecture body, filters out non-register signals
(temporaries, ports, etc.), and emits a paste-ready force/release block
suitable for inclusion in a testbench process.

Usage:
    gen_force_block.py <translated.vhd> [--instance dut] [--phases 1|2|3]

See docs/force_state_coverage.md for the technique and rationale.
"""
import argparse
import re
import sys

# Signals to skip — these are iverilog-introduced temporaries / non-registers
SKIP_PREFIXES = ('tmp_ivl_', 'ivl_', '_')
SKIP_SUFFIXES = ()  # add if needed
# Signals containing these substrings are usually combinational, skip
SKIP_SUBSTR = ('_next', '_nxt', '_in', '_out', '_wire')

SIGNAL_RE = re.compile(
    r'^\s*signal\s+(\w+)\s*:\s*'
    r'(std_logic|std_ulogic|unsigned\(\s*(\d+)\s+downto\s+(\d+)\s*\))',
    re.IGNORECASE,
)


def parse_signals(path):
    sigs = []
    with open(path) as f:
        for line in f:
            m = SIGNAL_RE.match(line)
            if not m:
                continue
            name = m.group(1)
            if name.startswith(SKIP_PREFIXES):
                continue
            if any(s in name.lower() for s in SKIP_SUBSTR):
                continue
            type_text = m.group(2).strip()
            if type_text.lower().startswith('std_'):
                width = 1
            else:
                hi = int(m.group(3))
                lo = int(m.group(4))
                width = hi - lo + 1
            sigs.append((name, type_text, width))
    return sigs


def emit_force_value(width, pattern):
    """pattern: 'ones', 'AA', '55'"""
    if width == 1:
        return "'1'" if pattern == 'ones' else ("'1'" if pattern == 'AA' else "'0'")
    if pattern == 'ones':
        return '(others => \'1\')'
    # Build alternating bits
    if pattern == 'AA':
        bits = ''.join('1' if i % 2 == 0 else '0' for i in range(width))
    else:  # '55'
        bits = ''.join('0' if i % 2 == 0 else '1' for i in range(width))
    return f'"{bits}"'


def emit_block(sigs, instance, phases):
    out = []
    out.append(f'    -- Force-state block (auto-generated by gen_force_block.py)')
    out.append(f'    -- {len(sigs)} register signals')

    def emit_phase(label, pattern):
        out.append(f'    -- Phase: {label}')
        for name, ty, w in sigs:
            val = emit_force_value(w, pattern)
            out.append(f'    << signal {instance}.{name} : {ty} >> <= force {val};')
        out.append('    wait for 50 ns;')

    emit_phase('all-ones', 'ones')
    if phases >= 2:
        emit_phase('AA pattern', 'AA')
    if phases >= 3:
        emit_phase('55 pattern', '55')

    out.append('    -- Release all')
    for name, ty, _ in sigs:
        out.append(f'    << signal {instance}.{name} : {ty} >> <= release;')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('vhd_file')
    ap.add_argument('--instance', default='dut',
                    help='Instance label of the DUT in the testbench (default: dut)')
    ap.add_argument('--phases', type=int, default=2, choices=(1, 2, 3),
                    help='Number of force phases (1=ones only, 2=+AA, 3=+55)')
    args = ap.parse_args()

    sigs = parse_signals(args.vhd_file)
    if not sigs:
        print('no register signals found', file=sys.stderr)
        sys.exit(1)
    print(emit_block(sigs, args.instance, args.phases))


if __name__ == '__main__':
    main()
